### ISSUE TITLE
Make `unsafe_read_chan` and `unsafe_write_chan` unsafe

### ISSUE THREAD

**Issue by Munksgaard** [Munksgaard/session-types#13]
I think this would make a lot of sense, even though they aren't publicly exposed. That way we'd also have cleaner impls:

```rust
pub fn send(self, v: A) -> Chan<E, P> {
    unsafe {
        unsafe_write_chan(&self, v);
        transmute(self)
    }
}
```

Do you agree?

**Comment by Munksgaard** [comment]
@laumann: What do you think

**Comment by laumann** [comment]
We discussed this offline and agree that it makes sense to mark `unsafe_{read,write}_chan` unsafe (and change the names to `{read,write}_chan`) to indicate that they should not by themselves be considered safe.

**Comment by laumann** [comment]
Closing this - it's already fixed

**Comment by Munksgaard** [comment]
No it isn't, but I just created a pull-request.
