### ISSUE TITLE
Move to Github actions

### ISSUE THREAD

**Issue by Munksgaard** [Munksgaard/session-types#65]
Now that Travis is [closing down](https://news.ycombinator.com/item?id=25338983), perhaps we should look at moving to Github actions for our CI needs?

**Comment by kfl** [comment]
Great that you are doing this @Munksgaard 

A minor suggestion, why not give the workflow a better name than "Rust", for instance "Build and test"?

(I might have misunderstood how Github actions are working and are named.)

**Comment by Munksgaard** [comment]
Fixed by #66

**Comment by Munksgaard** [comment]
Good suggestion @kfl. I've updated the CI script in #69, take a look.
